#!/bin/bash

set -e -x

# for jq
PATH=/usr/local/bin:$PATH

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

payload=$(cat)

uri=$(echo "$payload" | jq -r '.source.uri')
oinkcode=$(echo "$payload" | jq -r '.source.oinkcode')

wget $uri.md5?oinkcode=$oinkcode -O hash.md5
cat hash.md5 | jq -R '.' | jq -s "map({md5: .})" >&3
