#!/bin/bash

set -e

# for jq
PATH=/usr/local/bin:$PATH

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

destination=$1

cat > $payload <&0

uri=$(jq -r '.source.uri' < $payload)
oinkcode=$(jq -r '.source.oinkcode' < $payload)
md5=$(jq -r '.version.md5' < $payload)

wget $uri?oinkcode=$oinkcode -O $destination/rules.tar.gz

# TODO: Verify hash

jq -n "{
  md5: {ref: $(echo $rules_hash | jq -R .)},
}" >&3
