#!/bin/bash

set -e -x

PATH=/usr/local/bin:$PATH

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

destination=$1

payload=$(cat)

uri=$(echo "$payload" | jq -r '.source.uri // ""')
oinkcode=$(echo "$payload" | jq -r '.source.oinkcode // ""')
md5=$(echo "$payload" | jq -r '.version.md5 // ""')

dest=$destination/${uri##*/}

if [ -n "$oinkcode" ]; then
  query="?oinkcode=$oinkcode"
else
  query=""
fi

wget $uri$query -O $dest
md5_computed=$(md5sum $dest | cut -f 1 -d ' ')

if [ -n "$md5" ] && [ "$md5" != "$md5_computed" ]; then
  echo "MD5 mismatch: expected $md5, got $md5_computed"
  exit 1
fi

jq -n "{
  md5: {ref: $(echo $md5_computed | jq -R .)},
}" >&3
