#!/bin/bash

set -e -x

# for jq
PATH=/usr/local/bin:$PATH

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

destination=$1

payload=$(cat)

uri=$(echo "$payload" | jq -r '.source.uri')
oinkcode=$(echo "$payload" | jq -r '.source.oinkcode')
md5=$(echo "$payload" | jq -r '.version.md5')

wget $uri?oinkcode=$oinkcode -P $destination

# TODO: Verify hash

jq -n "{
  md5: {ref: $(echo $rules_hash | jq -R .)},
}" >&3
